name: bread
description: "Bread"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  decimal: ^3.0.2
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  number_text_input_formatter: ^1.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
